# Generated by Django 2.2.10 on 2020-08-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200808_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='image',
            new_name='images',
        ),
    ]
