# Generated by Django 2.2.10 on 2020-08-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200808_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook',
            field=models.FileField(default='', upload_to='books'),
        ),
    ]
